version: 2
jobs:
  build:
    working_directory: ~/askbywho
    docker:
      - image: trenpixster/elixir:1.3.2
      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test