version: 2
jobs:
  build:
    working_directory: /home/ubuntu/askbywho
    docker:
      - image: trenpixster/elixir:1.3.2
      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - run:
         name: Setup Env
         command: |
          sudo apt update
          sudo apt-get install -y postgresql-client
          mix deps.get
      - run: mix ecto.create
      - run:
	 name: Setup testing and dogma 
	 command: | 
	  mix test
	  mix coveralls.post -t $COVERALLS_REPO_TOKEN
	  mix dogma
